name: aliyun_oss_flutter2
description: aliyun oss plugin for flutter. Use this plugin to upload、download、list files to aliyun oss.
version: 2.0.0
homepage: https://github.com/SUNbrightness/aliyun_oss/tree/main

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path: ^1.8.0
  http_parser: ^4.0.0
  xml: ^5.3.1
  crypto: ^3.0.1
  intl: ^0.17.0
  dio: ^4.0.0

flutter:
